### ISSUE TITLE
Fail when replacement not found

### ISSUE THREAD

**Issue by hurricane766** [eruizdechavez/grunt-string-replace#31]
I'm using grunt-string-replace to modify some connection parameters in javascript depending on the deployment endpoint. I'd like grunt to error out if no matches were found because the application will fail if the replacement doesn't happen.

Thanks

**Comment by eruizdechavez** [comment]
Having no matches is not necessarily an error; throwing an error here could break a lot of other projects using string replacing.

**Comment by hurricane766** [comment]
Well, yes, I wasn't trying to suggest it default to fail. But it would be nice to have an option.

**Comment by eruizdechavez** [comment]
@hurricane766 let me think about it (not for another year, I promise) and if I come with some sort of option I'll update it. I am doing some clean up and follow up on these issues.

**Comment by eruizdechavez** [comment]
@hurricane766 while updating other issues I remembered the plugin is already showing a log message if no replacements were made, although it is on the debug output. Would that be a good workaround for you for the time being?

**Comment by eruizdechavez** [comment]
You will need to include the option `saveUnchanged: false`.

```js
options: {
  saveUnchanged: false,
  replacements: [{
    pattern: /some pattern/ig,
    replacement: 'some replacement',
  }]
}
```

It will **not** create the file and show a log in the terminal like this:

```sh
$ grunt
Running "string-replace:dist" (string-replace) task
File foo/bar/baz.html not created; No replacements found.

Done, without errors.
```

**Comment by hurricane766** [comment]
I guess it depends on the context of how grunt-string-replace is being used. We're using it during deployment, so if it the string replace fails, but the rest of the deployment continues, we end up with a deployment that doesn't work.

The debug option at least gives the 'no replacements found' message which does help track the issue.
