### ISSUE TITLE
node version path different 

### ISSUE THREAD

**Issue by mhf-ir** [eruizdechavez/grunt-string-replace#37]
I use this on node 4.x works:

```
    'string-replace': {
      'remove': {
        files: {
          'public/lib/css/': 'public/lib/css/*.css'
        },
        options: {
          replacements: [
            {
              pattern: /(\@font\-face[^\}]+})/gm,
              replacement: ''
            }
          ]
        }
      }
    },
```
but did not work properly on 5.x. it will create `public/lib/css/public/lib/css/` ... path on folders ... do0uh !!!

this will work on node 5.x 
```
```
    'string-replace': {
      'remove': {
        files: {
          './': 'public/lib/css/*.css'
        },
        options: {
          replacements: [
            {
              pattern: /(\@font\-face[^\}]+})/gm,
              replacement: ''
            }
          ]
        }
      }
    },
```
```

**Comment by eruizdechavez** [comment]
There is a known error on Node.js v5.7.0. Be sure to use any v4.x or update to the latest v5.x version.

**Comment by mhf-ir** [comment]
is error still on node v5.10.1 ?

**Comment by mhf-ir** [comment]
?

**Comment by eruizdechavez** [comment]
Just ran all tests in v5.10.0, v5.10.1 and v5.11.0 and everything is working fine.
