### ISSUE TITLE
Replace strings on files by using string or regex patters.

### ISSUE THREAD

**Issue by peterbenoit** [eruizdechavez/grunt-string-replace#39]
Replace strings on files by using string or regex patterNs.

**Comment by eruizdechavez** [comment]
I do not understand. That is what this plugin actually does.

**Comment by michaelhodgins** [comment]
I think he's referring to the spelling mistake in the project's description.

**Comment by eruizdechavez** [comment]
@michaelhodgins yup, that is what it was meant. thanks for the note!
