### ISSUE TITLE
Doesn't take into account the directories and files created at runtime.

### ISSUE THREAD

**Issue by tHBp** [eruizdechavez/grunt-string-replace#41]
I have a grunt default task which calls multiple tasks, like creating a temporary directory and then in the same default task, I call the string-replace.
For example, ```    grunt.registerTask('default', ['copy','string-replace']);```
String replace doesn't throw any errors but doesn't replace anything.
If I call ```grunt string-replace``` after the task has ended, then it works as expected.
In short, the ```string-replace``` task doesn't work on the copied files from the copy task but after the grunt exits, then if I call ```grunt string-replace```, then it replaces the values.

**Comment by tHBp** [comment]
I was not passing the values properly.
Apologies for any inconvenience caused.
Closing the issue.

**Comment by eruizdechavez** [comment]
No worries. I was already replying to ask for an example of your grunt file. 

_Mischief managed_
